[theme]
primaryColor = "#f97316"
backgroundColor = "#020617"
secondaryBackgroundColor = "#0f172a"
textColor = "#e5e7eb"
font = "sans serif"
base = "dark"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false


